#!/bin/bash

sudo dnf check-update -y
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
sudo dnf update -y


echo "Welcome! This script will install essential packages and repositories on your Fedora system."
echo "Please wait while the necessary components are being installed... by Oguzhan D."
# Update PATH variable
echo "Updating PATH variable..."
export PATH="$HOME/.local/bin:$PATH"

# Install additional utilities: curl, git, neofetch
echo "Installing additional utilities: curl, git, neofetch..."
sudo dnf install -y curl git neofetch wget

# Install development tools for C and Python
echo "Installing development tools for C and Python..."
sudo dnf install -y gcc make gdb valgrind glibc-devel python3 python3-pip python3-virtualenv python3-ipython python3-devel

# Update PATH variable
echo "Updating PATH variable..."
export PATH="$HOME/.local/bin:$PATH"

# Install Python packages
echo "Installing Python packages..."
pip3 install --user numpy pandas matplotlib


# Enable RPM Fusion repositories
echo "Enabling RPM Fusion repositories..."
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Install multimedia codecs
echo "Installing multimedia codecs..."
sudo dnf group update -y sound-and-video
sudo dnf install -y gstreamer1-plugins-{bad-free,ugly-free,good,base} gstreamer1-libav
sudo dnf install -y gstreamer1-plugins-bad-freeworld gstreamer1-plugins-ugly
sudo dnf install -y ffmpeg ffmpeg-libs
sudo dnf install -y vlc

sudo dnf install java-17-openjdk-devel -y
java -version
echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk' >> ~/.bashrc
echo 'export PATH=$PATH:$JAVA_HOME/bin' >> ~/.bashrc
source ~/.bashrc


# Install Flatpak and enable Flathub repository
echo "Installing Flatpak and enabling Flathub repository..."
sudo dnf install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# Install Nvidia drivers
echo "Installing Nvidia drivers..."
sudo dnf upgrade --refresh -y
sudo dnf install -y akmod-nvidia
sudo dnf install -y xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs

# Add and install Visual Studio Code repository and package
echo "Installing Visual Studio Code..."
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
sudo dnf install -y code

# Add and install Sublime Text repository and package
echo "Installing Sublime Text..."
sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
sudo dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
sudo dnf install -y sublime-text

# Add and install Brave browser repository and package
echo "Installing Brave browser..."
sudo dnf install -y dnf-plugins-core
sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
sudo dnf install -y brave-browser

# Add and install Google Chrome browser
echo "Installing Google Chrome browser..."
sudo dnf install -y fedora-workstation-repositories
sudo dnf config-manager --set-enabled google-chrome
sudo dnf install -y google-chrome-stable

# Add and install Microsoft Edge browser
echo "Installing Microsoft Edge browser..."
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo dnf config-manager --add-repo https://packages.microsoft.com/yumrepos/edge
sudo dnf install -y microsoft-edge-stable
sudo wget https://raw.githubusercontent.com/OguzhanDUYAR/MyFixAppLinux/main/myfixfedora -O /usr/bin/myfixfedora && sudo chmod +x /usr/bin/myfixfedora && sudo wget https://raw.githubusercontent.com/OguzhanDUYAR/MyFixAppLinux/main/myfixfedora.desktop -O /usr/share/applications/myfixfedora.desktop


# Update system and reboot
echo "Updating system and preparing for reboot..."
sudo dnf check-update -y
neofetch
echo "All tasks completed successfully! Press Y key to reboot."
# Ask the user if they want to close the terminal
read -p "Do you want to close the terminal? (y/n): " answer

# Check the user's answer
if [[ $answer == "y" ]]; then
    sudo reboot
else
    echo "The terminal will remain open."
fi



